### ISSUE TITLE
ask heroku admin to remove unused apps

### ISSUE THREAD

**Issue by garbas** [garbas/mozilla-releng#33]
apps to be removed:
- https://dashboard.heroku.com/apps/releng-stag-database
- https://dashboard.heroku.com/apps/relengapi-master
- https://dashboard.heroku.com/apps/relengapi-staging-clobberer
- https://dashboard.heroku.com/apps/relengapi-prod-clobberer
- https://dashboard.heroku.com/apps/relengapi-prod-postgres
- https://dashboard.heroku.com/apps/relengapi-staging-postgres

also this pipeline needs to be removed:
- https://dashboard.heroku.com/pipelines/6e02ffe0-7bc4-43ee-a402-2c0f7820e554

**Comment by garbas** [comment]
all of the above apps/pipeline were created by me (@garbas), but i don't have permissions to remove them

**Comment by garbas** [comment]
asked ``garndt`` (as admin to remove) and ``catlee`` to review i'm not making any mistake.

**Comment by garbas** [comment]
![2016-08-24-142910_839x51_scrot](https://cloud.githubusercontent.com/assets/20208/17930553/274f2858-6a07-11e6-8da5-570dc53b3cd8.png)

**Comment by gregarndt** [comment]
All of these should be removed now.  Thank you for those links, super helpful!

**Comment by garbas** [comment]
@gregarndt tnx you!!!

just for further reference (it is anyway already in the docs). current apps managed by this repo are
![2016-08-25-175729_359x173_scrot](https://cloud.githubusercontent.com/assets/20208/17977197/03041ab8-6af1-11e6-86eb-9d092c6d73e5.png)
